version: '2'

services:
  traefik:
    image: traefik:latest
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8000:8000"
    networks:
      - webserver_webLAN
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    container_name: traefik
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    

networks:
  webserver_webLAN:
    external: true
