version: '2'


services:

  web:
    image: nginx:latest
    ports:
      - "${PORT_HTTP}:80"
    volumes:
      - ./www_site:/www_site
      - ./site.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Path:/sqli"
    links:
      - php
      - mysql

  php:
    build: ./php/ 
    volumes:
      - ./www_site:/www_site
    labels:
      - "traefik.enable=false"
    links:
      - mysql

  mysql:
    build: ./mysql/
    container_name: ctfsqli_mysql_1
    labels:
      - "traefik.enable=false"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword

