#
#
#
version: '2'


services:
  traefik:
    image: traefik:latest
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    #expose:
      # traefik dashboard port
     # - 8000
    networks:
      - webLAN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./certs/:/certs/
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Path:/yoloboard"
      # get md5 from htpasswd or http://www.htaccesstools.com/htpasswd-generator/
      # and then double all $ to $$ to avoid docker-compose
      # yoloboard: md5(yoloboard)
      # echo $(htpasswd -nbB <USER> "<PASS>") | sed -e s/\\$/\\$\\$/g
      # sudo apt install apache2-utils
      # echo $(htpasswd -nbB yoloboard "yoloboard") | sed -e s/\\$/\\$\\$/g
      - "traefik.frontend.auth.basic=yoloboard:$$2y$$05$$kkeDkLd.htjb7sMk7eTynuqJeyl8EaQGVH8J0d9INuRD4fIrNk/Ba"
      - "traefik.port: 8000"
    container_name: traefik

  webserver_nginx:
    image: nginx:latest
    container_name: webserver_nginx
    ports:
      - "8888:80"
    networks:
      - webLAN
    volumes:
      - ./www_site:/www_site
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - webserver_php
      - webserver_mysql
    labels:
      - "traefik.backend=webserver"
      - "traefik.docker.network=web_server_webLAN"
      - "traefik.frontend.rule=PathPrefix: /index"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"




  webserver_php:
    #image: php:7-fpm
    build: php/.
    container_name: webserver_php
    volumes:
      - ./www_site:/www_site
    networks:
      - webLAN
      - sqlLAN
    links:
      - webserver_mysql
    labels:
      - "traefik.enable=false"

  webserver_mysql:
    build: ./mysql/
    container_name: webserver_mysql
    # for debug
    #ports:
    #  - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=AZ56FG78HJZE34
    networks:
        - sqlLAN
    labels:
      - "traefik.enable=false"
      
networks:
  webLAN:
    driver: bridge
  sqlLAN:
    driver: bridge