#
#
#
version: '2'


services:
  web:
    image: nginx:latest
    ports:
      - "8888:80"
    networks:
      - webLAN
    volumes:
      - ./www_site:/www_site
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php


  php:
    image: php:7-fpm
    #build: php/.
    volumes:
      - ./www_site:/www_site
    networks:
      - webLAN

networks:
  webLAN:
    driver: bridge