#
#
# La valeur de PORT_VSFTP est définie dans .env
#

vsftpd:
  build: . 
  container_name: ctf-exploit
  ports:
    - "${PORT_VSFTP}:21"
    - "${PORT_VSFTP_BACKDOOR}:${PORT_VSFTP_BACKDOOR}"
  restart: always